Графика для всех страниц
htmlacademy-htmlcss/2263217-gllacy-36 pull request #3
Opened 2023-01-26 18:51 UTC by komradlew

Вставка контентных изображений на основную страницу и в каталог

2023-01-29 16:36 UTC, pavel-nyukalo requested changes
Насчет вот этих картинок:

1. 
![image](https://user-images.githubusercontent.com/52506235/215338786-0eff4b35-f4b2-4750-a054-bf81610669ff.png)


Я бы экспортнул их без полупрозрачности, чтобы если вдруг понадобится ее изменить (сейчас это 40%, но вдруг дизайнер скажет надо 45%), то сделать это через CSS. Через CSS легче, чем экспортировать новую картинку.

Можно скопировать макет себе, и вот тут поменять на 100%

![image](https://user-images.githubusercontent.com/52506235/215338775-4631353b-e835-4ef4-a637-9a2b2b6122eb.png)

2. 

Вот эти картинки лучше в png сделать, поскольку нам нужно полупрозрачность в фоне

![image](https://user-images.githubusercontent.com/52506235/215340516-e562ab78-6805-4415-97ba-03126ffd241a.png)

![image](https://user-images.githubusercontent.com/52506235/215340522-4fb1c8f2-9739-49a0-9f00-71d6944bcb5a.png)

А у jpg будет белый фон

2023-01-29 16:36 UTC, pavel-niukalo commented on catalog.html
> +          <img class="logo" src="images/logo.svg" height="55.72" width="137" alt="Логотип магазина мороженого Gllacy Shop.">
Дробные значения не пройдут валидацию, поэтому лучше округлить

2023-01-29 16:36 UTC, pavel-niukalo commented on catalog.html
> +              <img class="card-image" src="images/filling-1.jpg" height="168" width="168">
Изображениям обязательно нужно задавать `alt`

Да, он может быть пустым, если рядом есть заголовок, который описывает содержимое картинки, но присутствовать обязан

2023-01-29 16:36 UTC, pavel-niukalo commented on images/Arrow-down.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none"><path fill="#2D3440" fill-rule="evenodd" d="M3.808 6.195a.667.667 0 1 0-.943.943l4.66 4.66a.665.665 0 0 0 .95.006l.006-.005
Насчет названий файлов:
1. Они должны быть прописаны строчными буквами
![image](https://user-images.githubusercontent.com/52506235/215338226-264e0244-db0a-4312-9548-064507bb9e66.png)

2. Разделители слов должны быть одинаковыми

![image](https://user-images.githubusercontent.com/52506235/215338247-9f65c63f-f8b5-4613-8a00-94da8fd18abc.png)

Сейчас есть как и `-`, так и `_`

2023-01-29 16:36 UTC, pavel-nyukalo commented on styles/styles.css
> +  background: url(../images/wafer-border.png) no-repeat;
Для единообразия давай везде писать кавычки в `url`. Как в `font-face`

2023-01-29 16:36 UTC, pavel-nyukalo commented on styles/styles.css
> +nav {
По тегам стилизация запрещена

2023-01-30 17:25 UTC, pavel-nyukalo requested changes

2023-01-30 17:25 UTC, pavel-nyukalo commented on index.html
> +        <a class="form-link form-btn" href="#">Форма обратной связи</a>
Напишу тут.

Разный тип кавычек

![image](https://user-images.githubusercontent.com/52506235/215547639-d7eea8f9-59ef-471a-95eb-4669632800d8.png)

Во-первых, завернут критерий по единообразности

Во-вторых, ругается валидатор

![image](https://user-images.githubusercontent.com/52506235/215547876-d630d9d9-7116-4608-9c73-83c08b30e27f.png)

Давай проверим все кавычки в обоих файлах

2023-01-30 17:25 UTC, pavel-nyukalo commented on catalog.html
> +              <img class="card-image" src="images/filling-12.png" height="168" width="168" alt="">
Тоже напишу тут, гит не показывает что там есть изменения, а заметил только сейчас

У ссылки нужно убрать `type` - его у нее нет. Замени на `href="#"`

![image](https://user-images.githubusercontent.com/52506235/215548353-e45d2196-2f11-4ee1-8e0a-4e2e8f20cc69.png)

2023-01-30 17:25 UTC, pavel-nyukalo commented on styles/styles.css
> +.form-link, .footer-menu-link, .logo-htmlacademy, .breadcrumbs-link, .card-link, .card-button, .pagination-link {
На подумать к след. заданию:

может имеет смысл дать им общий класс? Чтобы не перечислять так много классов через запятую. Просто в разметке у элемента будет два класса например

Например
```html
<a class="nav-logo common-link" href="index.html">
<a class="nav-link common-link" href="">

и тд
```

В `common-link` как раз будут вот эти стили общие, а в уникальных классах какие-то уже уникальные свойства

2023-01-30 19:40 UTC, komradlew commented on index.html
> +        <a class="form-link form-btn" href="#">Форма обратной связи</a>
проверил, поправил, но странно

пользуюсь и маком, и виндоноутом - не знаю, может, поэтому кавычки разные, буду внимательнее, спасибо

2023-01-30 19:53 UTC, komradlew commented on styles/styles.css
> +.form-link, .footer-menu-link, .logo-htmlacademy, .breadcrumbs-link, .card-link, .card-button, .pagination-link {
ну да, хотел, но такое простое решение почему-то из головы вылетело, спасибо

2023-01-31 13:09 UTC, pavel-nyukalo approved these changes

2023-01-31 13:09 UTC, merged